services:
  - type: web
    name: gridlinkx-app
    env: node
    runtime: node
    nodeVersion: 20
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: gridlinkx-db
          property: connectionString
    # Run database setup after the build
    postBuild:
      - command: node scripts/setup-db.js

databases:
  - name: gridlinkx-db
    plan: free
    databaseName: gridlinkx
    user: gridlinkx_user